disabled_rules: [] # rule identifiers to exclude from running

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

line_length: 150

shorthand_operator: warning

variable_name:
  min_length: # only min_length
    warning: 3 # only warning
  excluded: # excluded via string array
    - id
    - URL

nesting:
  type_level:
    warning: 2
